### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "couragesland77@gmail.com",
  "password": "i12345L"
}


