### Create profile (Admin)
POST http://localhost:8080/profile/create
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW5qb24wMQ==

{
  "name": "Kapitan",
  "surname": "Barbossa",
  "email": "ship@sea",
  "phone": "998997771100",
  "password": "kapitanb@rbossaship",
  "status": "ACTIVE",
  "role": "ROLE_USER"
}


### Update profile (Admin)
PUT localhost:8080/profile/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwMDAyMzAsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTcxNzA4NjYzMCwiaXNzIjoiS3VuVXpUZXN0In0.mm5b4QNX2eWPjPjRyjlNjdMKF1HRRDyUIg8R5dia2P8AvU11rQDZdH8FmKqbtatKcm4wVfeMbng6U3tQtwH6yw


{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "ali@mail.ru",
  "phone": "998911234567",
  "password": "Qwerty123",
  "status": "ACTIVE",
  "role": "ROLE_USER"
}


### Update Profile detail (ANY)
PUT localhost:8080/profile/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTcwODE1NTEsImlkIjo1LCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzE3MTY3OTUxLCJpc3MiOiJLdW5VelRlc3QifQ.HsuoxFgbd6E7e9eNpxmavuAdZ8PzGJEUIc54lMBKKkIewUVcyb6J8VqBpOrGWa3uomJAOJ913Pf9452Fkp_Isw

{
  "name": "Jek",
  "surname": "Jeckov"
}


### Get all with pagination
GET localhost:8080/profile/all_with_pagination


### Delete
DELETE localhost:8080/profile/delete/4


### Get all by filter
POST localhost:8080/profile/filter?page=1&size=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkyMTkxMjEsImlhdCI6MTcxNjYyNzEyMSwicm9sZSI6InRlc3QiLCJzaWduIjoiYWRmODk1MDJhZDAyYjBlNDJjNTgwYTNiYmE3NmMyNGQwNjlhYWRmMTQ5NWY2N2Y1ZmEwNjc5OTBlMTE4YjU4NiIsInN1YiI6Ijc0MDIifQ.JsGEGpML-svM4ZJe0C3v4vp49zoCWcm6W_MJFrmrx4s

{

  "createDateFrom": "2024-05-19T11:28",
  "createDateTo": "2024-05-22T22:00"

}

