### Create region
POST http://localhost:8080/region/create
Content-Type: application/json

{
  "orderNumber": 5,
  "nameUz": "Farg'ona",
  "nameRu": "Фергана",
  "nameEn": "Ferghana"
}


### Update by id
PUT localhost:8080/region/update/3
Content-Type: application/json

{
  "orderNumber": 3,
  "nameUz": "Andijon",
  "nameRu": "Андижан",
  "nameEn": "Andijan"
}


### Get all
GET localhost:8080/region/all


### Delete
DELETE localhost:8080/region/delete/4


### Get all by language with RequestParam
GET localhost:8080/region/lang?language=UZ


### Get all by language with RequestHeader
GET localhost:8080/region/lang




